namespace Maple.MonoGameAssistant.Core
{
    public enum EnumMonoFieldAttribute : uint
    {
        FIELD_ATTRIBUTE_FIELD_ACCESS_MASK = 0x0007,
        FIELD_ATTRIBUTE_COMPILER_CONTROLLED = 0x0000,
        FIELD_ATTRIBUTE_PRIVATE = 0x0001,
        FIELD_ATTRIBUTE_FAM_AND_ASSEM = 0x0002,
        FIELD_ATTRIBUTE_ASSEMBLY = 0x0003,
        FIELD_ATTRIBUTE_FAMILY = 0x0004,
        FIELD_ATTRIBUTE_FAM_OR_ASSEM = 0x0005,
        FIELD_ATTRIBUTE_PUBLIC = 0x0006,

        FIELD_ATTRIBUTE_STATIC = 0x0010,
        FIELD_ATTRIBUTE_INIT_ONLY = 0x0020,
        FIELD_ATTRIBUTE_LITERAL = 0x0040,
        FIELD_ATTRIBUTE_NOT_SERIALIZED = 0x0080,
        FIELD_ATTRIBUTE_SPECIAL_NAME = 0x0200,
        FIELD_ATTRIBUTE_PINVOKE_IMPL = 0x2000,

        /* For runtime use only */
        FIELD_ATTRIBUTE_RESERVED_MASK = 0x9500,
        FIELD_ATTRIBUTE_RT_SPECIAL_NAME = 0x0400,
        FIELD_ATTRIBUTE_HAS_FIELD_MARSHAL = 0x1000,
        FIELD_ATTRIBUTE_HAS_DEFAULT = 0x8000,
        FIELD_ATTRIBUTE_HAS_FIELD_RVA = 0x0100,



        FIELD_ATTRIBUTE_ENUM = FIELD_ATTRIBUTE_LITERAL | FIELD_ATTRIBUTE_HAS_DEFAULT
    }
}
