namespace Maple.MonoGameAssistant.Core
{
    public enum EnumMonoMetaTable
    {
        MONO_TABLE_MODULE,
        MONO_TABLE_TYPEREF,
        MONO_TABLE_TYPEDEF,
        MONO_TABLE_FIELD_POINTER,
        MONO_TABLE_FIELD,
        MONO_TABLE_METHOD_POINTER,
        MONO_TABLE_METHOD,
        MONO_TABLE_PARAM_POINTER,
        MONO_TABLE_PARAM,
        MONO_TABLE_INTERFACEIMPL,
        MONO_TABLE_MEMBERREF, /* 0xa */
        MONO_TABLE_CONSTANT,
        MONO_TABLE_CUSTOMATTRIBUTE,
        MONO_TABLE_FIELDMARSHAL,
        MONO_TABLE_DECLSECURITY,
        MONO_TABLE_CLASSLAYOUT,
        MONO_TABLE_FIELDLAYOUT, /* 0x10 */
        MONO_TABLE_STANDALONESIG,
        MONO_TABLE_EVENTMAP,
        MONO_TABLE_EVENT_POINTER,
        MONO_TABLE_EVENT,
        MONO_TABLE_PROPERTYMAP,
        MONO_TABLE_PROPERTY_POINTER,
        MONO_TABLE_PROPERTY,
        MONO_TABLE_METHODSEMANTICS,
        MONO_TABLE_METHODIMPL,
        MONO_TABLE_MODULEREF, /* 0x1a */
        MONO_TABLE_TYPESPEC,
        MONO_TABLE_IMPLMAP,
        MONO_TABLE_FIELDRVA,
        MONO_TABLE_UNUSED6,
        MONO_TABLE_UNUSED7,
        MONO_TABLE_ASSEMBLY, /* 0x20 */
        MONO_TABLE_ASSEMBLYPROCESSOR,
        MONO_TABLE_ASSEMBLYOS,
        MONO_TABLE_ASSEMBLYREF,
        MONO_TABLE_ASSEMBLYREFPROCESSOR,
        MONO_TABLE_ASSEMBLYREFOS,
        MONO_TABLE_FILE,
        MONO_TABLE_EXPORTEDTYPE,
        MONO_TABLE_MANIFESTRESOURCE,
        MONO_TABLE_NESTEDCLASS,
        MONO_TABLE_GENERICPARAM, /* 0x2a */
        MONO_TABLE_METHODSPEC,
        MONO_TABLE_GENERICPARAMCONSTRAINT
    }
}
